image_env_var_suffix: IMAGE
model_name_env_var_suffix: MODEL
env_var_delimiter: "_"

services:
  - name: out_of_domain_detector
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/ood-detection
    image_version: 1.8.1-cu117

    model_url: s3://emma-simbot/model/checkpoints/simbot_ood/simbot_ood_v7/

  - name: intent_extractor
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/policy
    image_version: 1.35.0-cu113

    model_url: s3://emma-simbot/model/checkpoints/simbot_nlu/simbot_nlu_v4.ckpt

  - name: instruction_predictor
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/policy
    image_version: 1.35.0-cu113

    model_url: s3://emma-simbot/model/checkpoints/simbot_action/simbot_action_v8.2_annotation3_iou0.5_bsz512_lr1e-4.ckpt

  - name: feature_extractor
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/perception
    image_version: 1.12.0-cu113

    model_url: s3://emma-simbot/misc_projects/floppy_aug/checkpoints/model_0300125.pth

  - name: profanity_filter
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/profanity-filter
    image_version: latest

  - name: confirmation_classifier
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/confirmation-classifier
    image_version: 1.3.0-cu116

    model_url: s3://emma-simbot/model/checkpoints/confirmation-classifier/3-way_v3/

  - name: compound_splitter
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/compound-splitter
    image_version: 1.5.1

    model_url: s3://emma-simbot/model/checkpoints/generic_planner/nlu-20230314-195801-calm-beagle.tar.gz

  - name: simbot_hacks
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/simbot-hacks
    image_version: 1.14.2

  - name: simbot_qa
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/simbot-qa
    image_version: 1.4.0

    model_url: s3://emma-simbot/model/checkpoints/simbot_qa/temp_cps/simbot_qa_nlu_v24_temp.tar.gz

  - name: placeholder_vision_model
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/color-matcher
    image_version: 1.1.2

    model_url: s3://emma-simbot/model/checkpoints/21.pth
