image_env_var_suffix: IMAGE
model_name_env_var_suffix: MODEL
env_var_delimiter: "_"

services:
  - name: out_of_domain_detector
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/ood-detection
    image_version: 1.6.0-cu117

    model_url: s3://emma-simbot/model/checkpoints/simbot_ood/simbot_ood_v7/

  - name: intent_extractor
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/policy
    image_version: 1.32.1-cu113

    model_url: s3://emma-simbot/model/checkpoints/simbot_nlu/nlu_annotations2_v2_iou0.1.ckpt

  - name: instruction_predictor
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/policy
    image_version: 1.32.1-cu113

    model_url: s3://emma-simbot/model/checkpoints/simbot_action/simbot_action_v8_annotation3_iou0.5_bsz512_lr1e-4.ckpt

  - name: feature_extractor
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/perception
    image_version: 1.10.2-cu113

    model_url: s3://emma-simbot/misc_projects/floppy_aug/checkpoints/model_0300125.pth

  - name: profanity_filter
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/profanity-filter
    image_version: latest

  - name: confirmation_classifier
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/confirmation-classifier
    image_version: 1.3.0-cu116

    model_url: s3://emma-simbot/model/checkpoints/confirmation-classifier/3-way_v2/end_to_end/

  - name: compound_splitter
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/compound-splitter
    image_version: 1.0.2

  - name: simbot_hacks
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/simbot-hacks
    image_version: 1.4.0

  - name: simbot_qa
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/simbot-qa
    image_version: 1.4.0

    model_url: s3://emma-simbot/model/checkpoints/simbot_qa/simbot_qa_nlu_v9.tar.gz
