image_env_var_suffix: IMAGE
model_name_env_var_suffix: MODEL
env_var_delimiter: "_"

services:
  - name: out_of_domain_detector
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/ood-detection
    image_version: 1.4.0-cu117

    model_url: s3://emma-simbot/model/checkpoints/simbot_ood/simbot_ood_v3/

  - name: intent_extractor
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/policy
    image_version: 1.21.0-cu113

    model_url: s3://emma-simbot/model/checkpoints/simbot_nlu/nlu_annotations0_v2.ckpt

  - name: instruction_predictor
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/policy
    image_version: 1.21.0-cu113

    model_url: s3://emma-simbot/model/checkpoints/simbot_action/simbot_action_v5_annotation0_v2_bsz512_lr1e-4.ckpt

  - name: feature_extractor
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/perception
    image_version: 1.8.2-cu113

    model_url: s3://emma-simbot/model/checkpoints/vinvl_vg_x152c4_simbot_v124_customised.pth

  - name: profanity_filter
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/profanity-filter
    image_version: latest

  - name: confirmation_classifier
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/confirmation-classifier
    image_version: 1.1.0-cu116

    model_url: s3://emma-simbot/model/checkpoints/confirmation-classifier/end_to_end/

  - name: compound_splitter
    image_repository_uri: 020417957102.dkr.ecr.us-east-1.amazonaws.com/emma/compound-splitter
    image_version: 1.0.2
