[tool.poetry]
name = "emma-experience-hub"
version = "0.1.0"
description = ""
authors = ["Amit Parekh <7276308+amitkparekh@users.noreply.github.com>"]

packages = [{ include = "emma_experience_hub", from = "src" }]

[tool.poetry.dependencies]
python = "~3.9"
typer = {extras = ["all"], version = "^0.6.1"}
torch = "^1.12.0"
rich = "^12.5.1"
pydantic = "^1.9.2"
boto3 = "^1.24.56"
python-dotenv = "^0.20.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
wemake-python-styleguide = "^0.16.1"
flake8 = "^4.0.1"
mypy = "^0.961"
pytest = "^7.1.2"
pre-commit = "^2.19.0"
poethepoet = "^0.14.0"
isort = "^5.10.1"
pytest-cases = "^3.6.13"

[tool.black]
line-length = 99

[tool.isort]
profile = "black"
combine_as_imports = true
lines_after_imports = 2
line_length = 99
known_first_party = ["emma_*"]

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools"]
build-backend = "poetry.core.masonry.api"
