x-deploy-gpu: &deploy-gpu
  resources:
    reservations:
      devices:
        - driver: nvidia
          device_ids: ["all"]
          capabilities: [gpu]

services:
  feature_extractor:
    environment:
      DEVICE_ID: "0"
    deploy: *deploy-gpu

  intent_extractor:
    environment:
      DEVICE: "cuda:0"
    deploy: *deploy-gpu

  instruction_predictor:
    environment:
      DEVICE: "cuda:0"
    deploy: *deploy-gpu

  out_of_domain_detector:
    environment:
      DEVICE: "cuda:0"
    deploy: *deploy-gpu

  confirmation_classifier:
    environment:
      DEVICE: "cuda:0"
    deploy: *deploy-gpu

  simbot_qa:
    environment:
      DEVICE: "cuda:0"
    deploy: *deploy-gpu

  placeholder_vision_model:
    environment:
      DEVICE: "cuda:0"
    deploy: *deploy-gpu
