version: "3.9"

services:
  otel_collector:
    container_name: otel_collector
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./configs/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"

  data_prepper:
    container_name: data_prepper
    image: opensearchproject/data-prepper:latest
    volumes:
      - ./configs/data-prepper-pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./configs/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
