x-deploy-gpu-0: &deploy-gpu-0
  resources:
    reservations:
      devices:
        - driver: nvidia
          device_ids: ["0"]
          capabilities: [gpu]

x-deploy-gpu-1: &deploy-gpu-1
  resources:
    reservations:
      devices:
        - driver: nvidia
          device_ids: ["1"]
          capabilities: [gpu]

x-deploy-gpu-2: &deploy-gpu-2
  resources:
    reservations:
      devices:
        - driver: nvidia
          device_ids: ["2"]
          capabilities: [gpu]

x-deploy-gpu-3: &deploy-gpu-3
  resources:
    reservations:
      devices:
        - driver: nvidia
          device_ids: ["3"]
          capabilities: [gpu]

version: "3.9"

services:
  feature_extractor:
    environment:
      DEVICE_ID: "0"
    deploy: *deploy-gpu-0

  intent_extractor:
    environment:
      DEVICE: "cuda:0"
    deploy: *deploy-gpu-1

  instruction_predictor:
    environment:
      DEVICE: "cuda:0"
    deploy: *deploy-gpu-2

  out_of_domain_detector:
    environment:
      DEVICE: "cuda:0"
    deploy: *deploy-gpu-3

  confirmation_classifier:
    environment:
      DEVICE: "cuda:0"
    deploy: *deploy-gpu-3

  simbot_qa:
    environment:
      DEVICE: "cuda:0"
    deploy: *deploy-gpu-3

  placeholder_vision_model:
    environment:
      DEVICE: "cuda:0"
    deploy: *deploy-gpu-3
