x-deploy-gpu-0: &deploy-gpu-0
  resources:
    reservations:
      devices:
        - driver: nvidia
          device_ids: ["0"]
          capabilities: [gpu]

x-deploy-gpu-1: &deploy-gpu-1
  resources:
    reservations:
      devices:
        - driver: nvidia
          device_ids: ["1"]
          capabilities: [gpu]

x-deploy-gpu-2: &deploy-gpu-2
  resources:
    reservations:
      devices:
        - driver: nvidia
          device_ids: ["2"]
          capabilities: [gpu]

x-deploy-gpu-3: &deploy-gpu-3
  resources:
    reservations:
      devices:
        - driver: nvidia
          device_ids: ["3"]
          capabilities: [gpu]

services:
  feature_extractor:
    deploy: *deploy-gpu-0

  intent_extractor:
    deploy: *deploy-gpu-1

  instruction_predictor:
    deploy: *deploy-gpu-2

  out_of_domain_detector:
    deploy: *deploy-gpu-3

  confirmation_classifier:
    deploy: *deploy-gpu-3
