x-deploy-gpu: &deploy-gpu
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: all
          capabilities: [gpu]

x-model-volume: &model-volume
  - type: bind
    source: ../storage/models
    target: /app/model

version: "3.9"

services:
  profanity_filter:
    container_name: profanity_filter
    image: heriot-watt/emma-simbot:profanity-filter
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8000/healthcheck
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    ports:
      - "5503:8000"
    entrypoint: python -m
    command:
      - profanity_filter.web

  utterance_generator:
    container_name: utterance_generator
    image: heriot-watt/emma-simbot:nlg
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:6000/ping
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    ports:
      - "5504:6000"
    entrypoint: python
    command:
      - src/emma_nlg/api/controllers/simbot.py

  feature_extractor:
    container_name: feature_extractor
    image: heriot-watt/emma-simbot:perception
    environment:
      LOG_LEVEL: "debug"
      DEVICE_ID: "0"
      CLASSMAP_TYPE: "simbot"
    ports:
      - "5500:5500"
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:5500/ping
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes: *model-volume
    deploy: *deploy-gpu
    entrypoint: python
    command: src/emma_perception/commands/run_server.py --config_file "src/emma_perception/constants/vinvl_x152c4_simbot.yaml" MODEL.WEIGHT "/app/model/vinvl_vg_x152c4_simbot.pth" MODEL.ROI_HEADS.NMS_FILTER "1" MODEL.ROI_HEADS.SCORE_THRESH "0.2" TEST.IGNORE_BOX_REGRESSION "False"

  intent_extractor:
    container_name: intent_extractor
    image: heriot-watt/emma-simbot:policy
    environment:
      LOG_LEVEL: debug
      DEVICE: "cuda:0"
      MODEL_NAME: "heriot-watt/emma-base"
      MODEL_CHECKPOINT_PATH: "/app/model/nlu_with_low_level.ckpt"
    ports:
      - "5501:6000"
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:6000/healthcheck
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes: *model-volume
    deploy: *deploy-gpu
    entrypoint: python
    command: src/emma_policy/commands/run_simbot_nlu.py

  instruction_predictor:
    container_name: instruction_predictor
    image: heriot-watt/emma-simbot:policy
    environment:
      LOG_LEVEL: debug
      DEVICE: "cuda:0"
      MODEL_CHECKPOINT_PATH: "/app/model/simbot_single_action.ckpt"
    ports:
      - "5502:6000"
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:6000/healthcheck
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes: *model-volume
    deploy: *deploy-gpu
    entrypoint: python
    command: src/emma_policy/commands/run_simbot_action_api.py

  out_of_domain_detector:
    container_name: out_of_domain_detector
    image: heriot-watt/emma-simbot:ood-detector
    environment:
      LOG_LEVEL: info
      DEVICE: "cuda:0"
      EMBEDDING_MODEL: "/app/model/sbert-simbot/"
      MODEL_CHECKPOINT_PATH: "/app/model/bgm_components2_data-1.joblib"
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:6500/healthcheck
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy: *deploy-gpu
    ports:
      - "5505:6500"
    entrypoint: python -m
    command:
      - emma_ood_detector.api.ood_detector
