name: Releases

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.9

jobs:
  labeler:
    name: Update labels
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4.0.0

  release:
    name: Release
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Git
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config user.name "emma-simbot-bot"
          git config user.email "gdgp7yme8hn6zghsuoms@feedly.email"
          git config --global url."https://${PAT}@github.com/".insteadOf "https://github.com/"

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Load cached Python
        uses: tespkg/actions-cache@v1
        id: python-cache
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}-${{ hashFiles('pyproject.toml') }}
          bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
          accessKey: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secretKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install dependencies
        run: |
          poetry install

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Load npm cache
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Perform release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          npm install --no-save @bjoluc/semantic-release-config-poetry
          npx semantic-release
